application: test-rtc
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /html
  static_dir: html

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /bower_components
  static_dir: bower_components

- url: /.*
  script: testrtc.app
  secure: always

libraries:
- name: jinja2
  version: latest
